version: '3.9'
services:
  db:
    image: postgres:14
    expose:
      - '5432'
    volumes:
      - lab-7-templating:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm start'
volumes:
  lab-7-templating: